# -*- coding: utf-8 -*-
"""zero-sen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZ0rGOoB7nZS4gwRboa4OS_FZ8L1gnCL
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

"""###Load Train Dataset"""

# emotion.csv

file_link = 'https://drive.google.com/file/d/1RYGc03-OEbLyo4_wgZMSqh_-hfNA-rYg/view?usp=drive_link'
file_id = file_link.split('/d/')[1].split('/')[0]
new_link = f'https://drive.google.com/uc?export=download&id={file_id}'

df = pd.read_csv(new_link, sep=';')
print(df.head())
print(f"\nDataset shape: {df.shape}")
print(f"Columns: {list(df.columns)}")

"""###Load Test Dataset"""

file = 'https://drive.google.com/file/d/123Xhipf8KGIX60cNtePbsrrZp65lKYbj/view?usp=drive_link'
id = file.split('/d/')[1].split('/')[0]
new = f'https://drive.google.com/uc?export=download&id={id}'

# The file uses semicolon (;) as separator, not comma
df = pd.read_csv(new, sep=';')
print(df.head())
print(f"\nDataset shape: {df.shape}")
print(f"Columns: {list(df.columns)}")

"""# Actual Work with smaller dataset"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

emotion = pd.read_csv("text.csv")

emotion.info()

emotion['label'].unique()

"""# Dataset Imbalance"""

class_counts=emotion.groupby('label').size()
columns=['label','count','percentage']
outcome=[0,1,2,3,4,5]
count=list()
percentage=list()
for val in range(6):
    count.append(class_counts[val])
    percent=(class_counts[val]/len(emotion))*100
    percentage.append(percent)
imbalance_career=pd.DataFrame(list(zip(outcome,count,percentage)),columns=columns)
imbalance_career

"""# Data pre-process"""

print("Percentage(%) of null values per column:")
print(emotion.isnull().sum()/len(emotion)*100)

drop_col = ['Unnamed: 0']
emotion_new = emotion.drop(drop_col, axis=1)
emotion_new.info()



# Create a smaller sample of the dataset with equal numbers of all unique labels
emotion_sample = emotion_new.groupby('label').apply(lambda x: x.sample(n=min(len(x), 200), random_state=42)).reset_index(drop=True) # You can change the number of samples per label here

display(emotion_sample.info())
display(emotion_sample['label'].value_counts())

"""# *Now we use pretrained models to tune it according to this dataset*"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install transformers accelerate

from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification
import torch

# Load pre-trained tokenizer and model
tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')
model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=len(emotion_new['label'].unique()))

# Prepare the data for the model
encodings = tokenizer(list(emotion_sample['text']), truncation=True, padding=True, max_length=128)

class EmotionDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels.iloc[idx], dtype=torch.long) # Assuming labels are integers
        return item

    def __len__(self):
        return len(self.labels)

dataset = EmotionDataset(encodings, emotion_sample['label'])

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Encode sentiment labels to integers
label_encoder = LabelEncoder()
emotion_sample['label'] = label_encoder.fit_transform(emotion_sample['label'])

# Split the dataset into training and validation sets
train_texts, val_texts, train_labels, val_labels = train_test_split(list(emotion_sample['text']), emotion_sample['label'], test_size=0.2, random_state=42)

# Tokenize the training and validation texts
train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=128)
val_encodings = tokenizer(val_texts, truncation=True, padding=True, max_length=128)

# Create PyTorch datasets
train_dataset = EmotionDataset(train_encodings, pd.Series(train_labels))
val_dataset = EmotionDataset(val_encodings, pd.Series(val_labels))

from transformers import TrainingArguments

# Define training arguments
training_args = TrainingArguments(
    output_dir='./results',          # output directory
    num_train_epochs=3,              # number of training epochs
    per_device_train_batch_size=16,  # batch size for training
    per_device_eval_batch_size=64,   # batch size for evaluation
    warmup_steps=500,                # number of warmup steps for learning rate scheduler
    weight_decay=0.01,               # strength of weight decay
    logging_dir='./logs',            # directory for storing logs
    logging_steps=10,
    eval_strategy="epoch",
    report_to="none" # Corrected argument name
)

from transformers import Trainer

# Create a Trainer
trainer = Trainer(
    model=model,                         # the instantiated 🤗 Transformers model to be trained
    args=training_args,                  # training arguments, defined above
    train_dataset=train_dataset,         # training dataset
    eval_dataset=val_dataset,            # evaluation dataset
    tokenizer=tokenizer                  # the tokenizer is needed for the Trainer to know how to handle the data
)

# Train the model
trainer.train()

# Evaluate the model
eval_results = trainer.evaluate()
print(eval_results)

from transformers import pipeline

# Create a text classification pipeline using the fine-tuned model
sentiment_analyzer = pipeline("text-classification", model=model, tokenizer=tokenizer)

# Test the pipeline with a sample text
text_to_test = "অমর খুশি লাগতেসে"
result = sentiment_analyzer(text_to_test)

print(f"Text: {text_to_test}")
print(f"Predicted sentiment: {result}")

# Display the mapping between numerical labels and original emotion labels
label_mapping = dict(zip(label_encoder.transform(label_encoder.classes_), label_encoder.classes_))
print("Label mapping:")
print(label_mapping)

"""## *other models*"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

# Load pre-trained tokenizer and model
tokenizer_1 = AutoTokenizer.from_pretrained("xlm-roberta-base")
model_1 = AutoModelForSequenceClassification.from_pretrained("xlm-roberta-base", num_labels=len(emotion_new['label'].unique()))

# Prepare the data for the model
encodings = tokenizer_1(list(emotion_sample['text']), truncation=True, padding=True, max_length=128)

class EmotionDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels.iloc[idx], dtype=torch.long) # Assuming labels are integers
        return item

    def __len__(self):
        return len(self.labels)

dataset = EmotionDataset(encodings, emotion_sample['label'])

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Encode sentiment labels to integers
label_encoder = LabelEncoder()
emotion_sample['label'] = label_encoder.fit_transform(emotion_sample['label'])

# Split the dataset into training and validation sets
train_texts, val_texts, train_labels, val_labels = train_test_split(list(emotion_sample['text']), emotion_sample['label'], test_size=0.2, random_state=42)

# Tokenize the training and validation texts
train_encodings = tokenizer_1(train_texts, truncation=True, padding=True, max_length=128)
val_encodings = tokenizer_1(val_texts, truncation=True, padding=True, max_length=128)

# Create PyTorch datasets
train_dataset = EmotionDataset(train_encodings, pd.Series(train_labels))
val_dataset = EmotionDataset(val_encodings, pd.Series(val_labels))

from transformers import TrainingArguments

# Define training arguments
training_args = TrainingArguments(
    output_dir='./results',          # output directory
    num_train_epochs=3,              # number of training epochs
    per_device_train_batch_size=16,  # batch size for training
    per_device_eval_batch_size=64,   # batch size for evaluation
    warmup_steps=500,                # number of warmup steps for learning rate scheduler
    weight_decay=0.01,               # strength of weight decay
    logging_dir='./logs',            # directory for storing logs
    logging_steps=10,
    eval_strategy="epoch",
    report_to="none" # Corrected argument name
)

from transformers import Trainer

# Create a Trainer
trainer_1 = Trainer(
    model=model_1,                         # the instantiated 🤗 Transformers model to be trained
    args=training_args,                  # training arguments, defined above
    train_dataset=train_dataset,         # training dataset
    eval_dataset=val_dataset,            # evaluation dataset
    tokenizer=tokenizer_1                  # the tokenizer is needed for the Trainer to know how to handle the data
)

# Train the model
trainer_1.train()

eval_results = trainer_1.evaluate()
print(eval_results)

from transformers import pipeline

# Create a text classification pipeline using the fine-tuned model
sentiment_analyzer = pipeline("text-classification", model=model_1, tokenizer=tokenizer_1)

# Test the pipeline with a sample text
text_to_test = "I am excited for tomorrow!"
result = sentiment_analyzer(text_to_test)

print(f"Text: {text_to_test}")
print(f"Predicted sentiment: {result}")

"""# Pretrained but no fine tune in data (text classification approach)"""

from transformers import pipeline

"""## *J-hartmann*"""

classifier = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    return_all_scores=True
)

text = "I am so excited for tomorrow!"
results = classifier(text)

for r in results[0]:
    print(f"{r['label']}: {r['score']:.4f}")

text = "ami onek khushi"
results = classifier(text)

for r in results[0]:
    print(f"{r['label']}: {r['score']:.4f}")

sentences = [
    "ami onek khushi",
    "Ami khub dukkho paichi",
    "I am angry right now!"
]

results = classifier(sentences)

for sentence, prediction in zip(sentences, results):
    print(f"\nText: {sentence}")
    for r in prediction:
        print(f"  {r['label']}: {r['score']:.4f}")

"""## *SamLowe*"""

from transformers import pipeline
classifier_1 = pipeline("text-classification", model="SamLowe/roberta-base-go_emotions", return_all_scores=True)

text = "I am so excited for tomorrow!"
results = classifier_1(text)

for r in results[0]:
    print(f"{r['label']}: {r['score']:.4f}")

text = "ami onek khushi"
results = classifier_1(text)

for r in results[0]:
    print(f"{r['label']}: {r['score']:.4f}")

sentences = [
    "ami onek khushi",
    "Ami khub dukkho paichi",
    "I am angry right now!"
]

results = classifier_1(sentences)

for sentence, prediction in zip(sentences, results):
    print(f"\nText: {sentence}")
    for r in prediction:
        print(f"  {r['label']}: {r['score']:.4f}")

"""## *bhadresh-savani*"""

classifier_2 = pipeline("text-classification", model="bhadresh-savani/distilbert-base-uncased-emotion", return_all_scores=True)

text = "I am so excited for tomorrow!"
results = classifier_2(text)

for r in results[0]:
    print(f"{r['label']}: {r['score']:.4f}")

text = "ami onek khushi"
results = classifier_2(text)

for r in results[0]:
    print(f"{r['label']}: {r['score']:.4f}")

sentences = [
    "ami onek khushi",
    "Ami beshi dukkho paisi",
    "I am angry right now!"
]

results = classifier_2(sentences)

for sentence, prediction in zip(sentences, results):
    print(f"\nText: {sentence}")
    for r in prediction:
        print(f"  {r['label']}: {r['score']:.4f}")

"""## *cardiffnlp*"""

classifier_3 = pipeline("text-classification", model="cardiffnlp/twitter-roberta-base-emotion", return_all_scores=True)

text = "I am so excited for tomorrow!"
results = classifier_3(text)

for r in results[0]:
    print(f"{r['label']}: {r['score']:.4f}")

text = "ami onek khushi"
results = classifier_3(text)

for r in results[0]:
    print(f"{r['label']}: {r['score']:.4f}")

sentences = [
    "ami onek khushi",
    "Ami beshi dukkho paisi",
    "I am angry right now!"
]

results = classifier_3(sentences)

for sentence, prediction in zip(sentences, results):
    print(f"\nText: {sentence}")
    for r in prediction:
        print(f"  {r['label']}: {r['score']:.4f}")

"""# NLI approach"""

from transformers import pipeline

# multilingual NLI model (good zero-shot cross-lingual)
clf = pipeline("zero-shot-classification",
               model="MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7",
               device=0)  # set device=-1 for CPU

labels = ["joy","sadness","anger","fear","disgust","surprise","neutral"]

text = "ami onek khushi"  # example Banglish
res = clf(text, candidate_labels=labels, hypothesis_template="This text expresses {}.")
print(res)  # label and scores

# multilingual NLI model (good zero-shot cross-lingual)
clf_1 = pipeline("zero-shot-classification",
               model="joeddav/xlm-roberta-large-xnli",
               device=0)  # set device=-1 for CPU

labels = ["joy","sadness","anger","fear","disgust","surprise","neutral"]

text = "ami onek khushi"  # example Banglish
res = clf_1(text, candidate_labels=labels, hypothesis_template="This text expresses {}.")
print(res)  # label and scores

# multilingual NLI model (good zero-shot cross-lingual)
clf_2 = pipeline("zero-shot-classification",
               model="facebook/bart-large-mnli",
               device=0)  # set device=-1 for CPU

labels = ["joy","sadness","anger","fear","disgust","surprise","neutral"]

text = "ami onek khushi"  # example Banglish
res = clf_2(text, candidate_labels=labels, hypothesis_template="This text expresses {}.")
print(res)  # label and scores

clf_3 = pipeline("zero-shot-classification",
               model="MoritzLaurer/deberta-v3-large-zeroshot-v2.0",
               device=0)  # set device=-1 for CPU

labels = ["joy","sadness","anger","fear","disgust","surprise","neutral"]

text = "ami onek khushi"  # example Banglish
res = clf_3(text, candidate_labels=labels, hypothesis_template="This text expresses {}.")
print(res)  # label and scores

clf_4 = pipeline("zero-shot-classification",
               model="cross-encoder/nli-deberta-v3-base",
               device=0)  # set device=-1 for CPU

labels = ["joy","sadness","anger","fear","disgust","surprise","neutral"]

text = "ami onek khushi"  # example Banglish
res = clf_4(text, candidate_labels=labels, hypothesis_template="This text expresses {}.")
print(res)  # label and scores

"""# **Train with EN, BN, RN data**

At first we preprocess the data from Kaggle, link in doc file (last link)

link: https://www.kaggle.com/datasets/nit003/bangla-youtube-sentiment-and-emotion-datasets

"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

ds = pd.read_csv("Emotion.csv", sep=';')
ds

ds.info()

ds['emotion'].unique()

emotion_counts = ds['emotion'].value_counts()
emotion_percentages = ds['emotion'].value_counts(normalize=True) * 100

imbalance_df = pd.DataFrame({
    'count': emotion_counts,
    'percentage': emotion_percentages
})

print("Data imbalance for 'emotion' column:")
display(imbalance_df)

lan_counts = ds['lan'].value_counts()
lan_percentages = ds['lan'].value_counts(normalize=True) * 100

imbalance_df = pd.DataFrame({
    'count': lan_counts,
    'percentage': lan_percentages
})

print("Data imbalance for 'lan' column:")
display(imbalance_df)



ds_filtered = ds[ds['lan'] == 'RN'].copy()
print(f"Original dataset shape: {ds.shape}")
print(f"Filtered dataset shape: {ds_filtered.shape}")
display(ds_filtered.head())

emotion_counts = ds_filtered['emotion'].value_counts()
emotion_percentages = ds_filtered['emotion'].value_counts(normalize=True) * 100

imbalance_df = pd.DataFrame({
    'count': emotion_counts,
    'percentage': emotion_percentages
})

print("Data imbalance for 'emotion' column:")
display(imbalance_df)

ds_no_duplicates = ds_filtered.drop_duplicates().copy()
print(f"Dataset shape before dropping duplicates: {ds_filtered.shape}")
print(f"Dataset shape after dropping duplicates: {ds_no_duplicates.shape}")
display(ds_no_duplicates.head())

ds_no_duplicates

drop_col = ['id', 'lan', 'domain']
emotion_rn = ds_no_duplicates.drop(drop_col, axis=1)
emotion_rn.info()

from transformers import pipeline
from tqdm.auto import tqdm

# multilingual NLI model (good zero-shot cross-lingual)
clf = pipeline("zero-shot-classification",
               model="MoritzLaurer/mDeBERta-v3-base-xnli-multilingual-nli-2mil7",
               device=0)  # set device=-1 for CPU

labels = ["joy","none","disgust","anger","surprise","sad","others","fear"]

# Create lists to store actual and predicted labels
actual_labels = []
predicted_labels = []

# Sample 10% of the emotion_rn DataFrame
emotion_rn_sample = emotion_rn.sample(frac=0.1, random_state=42)

# Iterate through the sampled DataFrame
for index, row in tqdm(emotion_rn_sample.iterrows(), total=len(emotion_rn_sample)):
    text = row['text']
    actual_label = row['emotion']

    # Get predictions from the zero-shot classifier
    res = clf(text, candidate_labels=labels, hypothesis_template="This text expresses {}.")

    # Get the predicted label (the one with the highest score)
    predicted_label = res['labels'][0]

    actual_labels.append(actual_label)
    predicted_labels.append(predicted_label)

# Now you have lists of actual and predicted labels, you can evaluate the performance
# For example, you can use scikit-learn's classification_report or accuracy_score
print("Finished classifying texts. You can now evaluate the results using actual_labels and predicted_labels.")

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(actual_labels, predicted_labels)
print(f"Accuracy of the zero-shot classification model: {accuracy:.4f}")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import numpy as np

# Get the unique labels from both actual and predicted labels
unique_labels = np.unique(np.concatenate((actual_labels, predicted_labels)))

# Compute the confusion matrix
cm = confusion_matrix(actual_labels, predicted_labels, labels=unique_labels)

# Display the confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=unique_labels)
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()

# multilingual NLI model (good zero-shot cross-lingual)
clf_1 = pipeline("zero-shot-classification",
               model="joeddav/xlm-roberta-large-xnli",
               device=0)  # set device=-1 for CPU

labels = ["joy","none","disgust","anger","surprise","sad","others","fear"]

# Create lists to store actual and predicted labels
actual_labels1 = []
predicted_labels1 = []

# Sample 10% of the emotion_rn DataFrame
emotion_rn_sample = emotion_rn.sample(frac=0.1, random_state=42)

# Iterate through the sampled DataFrame
for index, row in tqdm(emotion_rn_sample.iterrows(), total=len(emotion_rn_sample)):
    text = row['text']
    actual_label = row['emotion']

    # Get predictions from the zero-shot classifier
    res = clf_1(text, candidate_labels=labels, hypothesis_template="This text expresses {}.")

    # Get the predicted label (the one with the highest score)
    predicted_label1 = res['labels'][0]

    actual_labels1.append(actual_label)
    predicted_labels1.append(predicted_label)

# Now you have lists of actual and predicted labels, you can evaluate the performance
# For example, you can use scikit-learn's classification_report or accuracy_score
print("Finished classifying texts. You can now evaluate the results using actual_labels and predicted_labels.")

accuracy1 = accuracy_score(actual_labels1, predicted_labels1)
print(f"Accuracy of the zero-shot classification model: {accuracy1:.4f}")

# Compute the confusion matrix
cm1 = confusion_matrix(actual_labels1, predicted_labels1, labels=unique_labels)

# Display the confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm1, display_labels=unique_labels)
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()

from transformers import pipeline
from tqdm.auto import tqdm

# multilingual NLI model (good zero-shot cross-lingual)
clf_2 = pipeline("zero-shot-classification",
               model="facebook/bart-large-mnli",
               device=0)  # set device=-1 for CPU

labels = ["joy","none","disgust","anger","surprise","sad","others","fear"]

# Create lists to store actual and predicted labels
actual_labels = []
predicted_labels = []

# Sample 10% of the emotion_rn DataFrame
emotion_rn_sample = emotion_rn.sample(frac=0.1, random_state=42)

# Iterate through the sampled DataFrame
for index, row in tqdm(emotion_rn_sample.iterrows(), total=len(emotion_rn_sample)):
    text = row['text']
    actual_label = row['emotion']

    # Get predictions from the zero-shot classifier
    res = clf_2(text, candidate_labels=labels, hypothesis_template="This text expresses {}.")

    # Get the predicted label (the one with the highest score)
    predicted_label = res['labels'][0]

    actual_labels.append(actual_label)
    predicted_labels.append(predicted_label)

# Now you have lists of actual and predicted labels, you can evaluate the performance
# For example, you can use scikit-learn's classification_report or accuracy_score
print("Finished classifying texts. You can now evaluate the results using actual_labels and predicted_labels.")

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(actual_labels, predicted_labels)
print(f"Accuracy of the zero-shot classification model: {accuracy:.4f}")

# Get the unique labels from both actual and predicted labels
unique_labels = np.unique(np.concatenate((actual_labels, predicted_labels)))

# Compute the confusion matrix
cm = confusion_matrix(actual_labels, predicted_labels, labels=unique_labels)

# Display the confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=unique_labels)
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()